export const userFilterableFields = [
  'searchTerm',
  'industry',
  'subIndustry',
  'category',
  'subCategory',
  'skills',
  'jobTitle',
  'experienceLevel',
  'availableHours',
  'hourlyPayInUSD',
  'yearsOfExperience',
  'locationPreference',
  'lookingFor',
];

export const userSearchableFields = [
  'industry',
  'subIndustry',
  'category',
  'subCategory',
  'skills',
  'jobTitle',
  'experienceLevel',
  'availableHours',
  'hourlyPayInUSD',
  'yearsOfExperience',
  'locationPreference',
  'lookingFor',
];
